DROP DATABASE IF EXISTS eggnews;
CREATE DATABASE IF NOT EXISTS eggnews;
USE eggnews;

CREATE TABLE role (
  id_role INT AUTO_INCREMENT NOT NULL,
  name ENUM('ROLE_USER','ROLE_ADMIN') DEFAULT 'ROLE_USER' NOT NULL,
  PRIMARY KEY (id_role)
) ENGINE = INNODB;

INSERT INTO role (name) VALUES ('ROLE_USER');
INSERT INTO role (name) VALUES ('ROLE_ADMIN');

CREATE TABLE image (
  id_image INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(150) NOT NULL,
  url VARCHAR(200) NOT NULL,
  PRIMARY KEY (id_image)
) ENGINE = INNODB;

CREATE TABLE user (
  id_user BIGINT NOT NULL,
  email VARCHAR(150) NOT NULL,
  password VARCHAR(300) NOT NULL,
  names VARCHAR(100) NOT NULL,
  surnames VARCHAR(100) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  id_role INT NOT NULL,
  PRIMARY KEY (id_user),
  FOREIGN KEY (id_role) REFERENCES role (id_role)
) ENGINE = INNODB;

CREATE TABLE user_sequence (
  next_val BIGINT NOT NULL
) ENGINE = INNODB;

INSERT INTO user_sequence VALUES (1);

CREATE TABLE news (
  id_news BIGINT NOT NULL,
  title VARCHAR(150) NOT NULL,
  body VARCHAR(2500) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  id_user BIGINT NOT NULL,
  id_image INT NOT NULL,
  PRIMARY KEY (id_news),
  FOREIGN KEY (id_user) REFERENCES user (id_user),
  FOREIGN KEY (id_image) REFERENCES image (id_image)
) ENGINE = INNODB;

CREATE TABLE news_sequence (
  next_val BIGINT NOT NULL
) ENGINE = INNODB;

INSERT INTO news_sequence VALUES (1);